### ISSUE TITLE
Clean the dataset

### ISSUE THREAD

**Issue by Emekaborisama** [Emekaborisama/Sex4Grades#1]
The dataset consists of tweets extracted from twitter and it needs to be cleaned and preprocess for analysis.

P.S you can use any tools or techniques to clean the dataset. 

Resources:

https://github.com/Emekaborisama/WeNoGetPresident (A similar project - Xenophobia)
https://towardsdatascience.com/extracting-twitter-data-pre-processing-and-sentiment-analysis-using-python-3-0-7192bd8b47cf
https://www.kaggle.com/ragnisah/text-data-cleaning-tweets-analysis
https://stackoverflow.com/questions/53578427/twitter-data-cleaning
https://github.com/agolokoz/twitter-cleaner

**Comment by nestornav** [comment]
Hi, do you want the process in a notebook? @Emekaborisama

**Comment by Emekaborisama** [comment]
Yes and CSV format too

**Comment by nestornav** [comment]
Okay I'll work on it.

**Comment by Emekaborisama** [comment]
Alright. Wish you good luck 🙌🏽

**Comment by lornamariak** [comment]
So I just did this. https://github.com/Emekaborisama/Sex4Grades/pull/8#issue-326470101

**Comment by nestornav** [comment]
@lornamariak you need to be more respectful when someone took the ticket. Take into account for the next time

**Comment by lornamariak** [comment]
Hey @nestornav, I literally saw this convo after making my pull request. I didn't know, but then again you can go ahead because different methods are all valid. I am sorry if it looks like I tackled your issue.🙂

**Comment by Emekaborisama** [comment]
@nestornav Lol. You can use your own approach. However, i haven't closed the issue yet. Meanwhile, i really look forward to seeing your PR

**Comment by eddyrene** [comment]
It's just me or the data is not clean yet?

**Comment by nestornav** [comment]
@eddyrene No, the data isn't clean. Soon @Emekaborisama will check my open PR and you will have the notebook that perform that in python.

**Comment by Emekaborisama** [comment]
@eddyrene the dataset has been cleaned. you can proceed
