### ISSUE TITLE
Exploratory Data Analysis 

### ISSUE THREAD

**Issue by Emekaborisama** [Emekaborisama/Sex4Grades#3]
This issue requires you to work with the cleaned dataset

In this issue, you will perform an EDA on the dataset to retrieve insight from the data.

Kindly check read.me file for more help 

Here are some resources that can help

https://www.kaggle.com/shivamb/seconds-from-disaster-text-eda-and-analysis
https://kaggle.com/ragnisah/text-data-cleaning-tweets-analysis

**Comment by nestornav** [comment]
@Emekaborisama  Somebody took this issue? I could work on it.

**Comment by Emekaborisama** [comment]
Go ahead

**Comment by nestornav** [comment]
Could you assign to me?

**Comment by Emekaborisama** [comment]
Yes i have done that

**Comment by Emekaborisama** [comment]
Look Forward to your PR

**Comment by nestornav** [comment]
I'm a little delayed but I'm working on that @Emekaborisama

**Comment by nestornav** [comment]
@Emekaborisama I updated the repo and I saw several dataset. For this issue the right one is this **sexforgrades.csv**?

**Comment by Emekaborisama** [comment]
No the right one is BBC Data set merged

https://github.com/Emekaborisama/Sex4Grades/blob/master/Data/updated/BBCAfricaEye_Merged.csv
