### ISSUE TITLE
Rename column name from 0, 1........................ to original name 

### ISSUE THREAD

**Issue by Emekaborisama** [Emekaborisama/Sex4Grades#5]
You will need to rename the columns from 0,1................ to [tweet.created_at, tweet.text, tweet.lang, tweet.user.location, tweet.user.verified, tweet.source, tweet.retweet_count, tweet.favorite_count]

**Comment by nestornav** [comment]
@Emekaborisama from my point of view, this issue could be an specification of the #1 issue

**Comment by Emekaborisama** [comment]
Yes. You are right

**Comment by Emekaborisama** [comment]
I created it to breakdown processes for beginner

**Comment by FernandoGarciafg** [comment]
New to GitHub, beginner but eager to participate, how can I do it?

**Comment by Emekaborisama** [comment]
Read more on using Pandas for data analysis

**Comment by nestornav** [comment]
I took this one with the first PR.

**Comment by Emekaborisama** [comment]
Cool. Go ahead. I look forward to see your PR
